# Site settings
title: Michael Salton
description: personal website
url: michaelsalton.github.io

# User settings
username: Michael Salton
user_description: 3+ years in software development, 2+ years in video game development
user_title: Software Developer
email: msalton6@gmail.com
instagram_username: michaelsalton_
linkedin_username: msalton
github_username:  michaelsalton

exclude: ['package.json', 'src' , 'node_modules']
